---
# site.yml for controller_custom_credentials

- name: Project controller_custom_credentials
  hosts: localhost
  gather_facts: no

  tasks:
  - name: Show Oops the Developer Exposed Protected Data
    user_module_wrong_way:
      name: '{{ custom_credential_username }}'
      password: '{{ custom_credential_password }}'
      private_ssh_key: '{{ custom_credential_private_ssh_key }}'
      public_ssh_key: '{{ custom _credential_public_ssh_key }}'
      state: present

  - name: Show the Developer Protected Valuable Sensitive Data
    user_module_correct_way:
      name: '{{ custom_credential_username }}'
      password: '{{ custom_credential_password }}'
      private_ssh_key: '{{ custom_credential_private_ssh_key }}'
      public_ssh_key: '{{ custom _credential_public_ssh_key }}'
      state: present